Feature/check out test
AnushkaRawatZ/zs-appium-generic-automation pull request #7
Opened 2024-11-26 06:53 UTC by AnushkaRawatZ

Implemented the checkout test

2024-11-26 07:13 UTC, swagata-zopsmart requested changes

2024-11-26 07:13 UTC, swagata-zopsmart commented on src/main/java/com/zs/pages/common/CheckoutPage.java
> +        wait.until(ExpectedConditions.elementToBeClickable(CommonUtils.getCheckoutLocators(appName, "debitCardRadio"))).click();
write test cases for other payment options as well

2024-11-26 07:13 UTC, swagata-zopsmart commented on src/test/java/base/BaseTest.java
> +    public final String appiumServerUrl="http://127.0.0.1:4723";
Can we move the urls to constant class and access it from there instead of hardcoding it in test

2024-11-26 07:13 UTC, swagata-zopsmart commented on src/test/java/test/CheckoutTest.java
> +
Can we name the test specific to payment options

2024-11-26 08:40 UTC, AnushkaRawatZ commented on src/test/java/base/BaseTest.java
> +    public final String appiumServerUrl="http://127.0.0.1:4723";
Done

2024-11-26 08:40 UTC, AnushkaRawatZ commented on src/test/java/test/CheckoutTest.java
> +
Sure.

2024-11-26 09:52 UTC, AnushkaRawatZ commented on src/main/java/com/zs/pages/common/CheckoutPage.java
> +        wait.until(ExpectedConditions.elementToBeClickable(CommonUtils.getCheckoutLocators(appName, "debitCardRadio"))).click();
I've added the check out test using cash on delivery payment method.

2024-11-27 10:53 UTC, merged

2024-11-27 10:53 UTC, swagata-zopsmart commented
Name the feature branch in camelCase